---

- name: copy .link profiles
  template:
    src: "systemd_networkd_profile.j2"
    dest: "/etc/systemd/network/{{ item.key }}.link"
    mode: 0644
  loop: "{{ systemd_networkd_link | dict2items }}"

- name: copy .netdev profiles
  template:
    src: "systemd_networkd_profile.j2"
    dest: "/etc/systemd/network/{{ item.key }}.netdev"
    mode: 0644
  loop: "{{ systemd_networkd_netdev | dict2items }}"

- name: copy .network profiles
  template:
    src: "systemd_networkd_profile.j2"
    dest: "/etc/systemd/network/{{ item.key }}.network"
    mode: 0644
  loop: "{{ systemd_networkd_network | dict2items }}"

# vim: set ts=2 sw=2:
