---

- name: copy .link profiles
  template:
    src: "systemd_networkd_profile.j2"
    dest: "/etc/systemd/network/{{ item.key }}.link"
    mode: 0644
  with_dict: "{{ systemd_networkd_link }}"

- name: copy .netdev profiles
  template:
    src: "systemd_networkd_profile.j2"
    dest: "/etc/systemd/network/{{ item.key }}.netdev"
    mode: 0644
  with_dict: "{{ systemd_networkd_netdev }}"

- name: copy .network profiles
  template:
    src: "systemd_networkd_profile.j2"
    dest: "/etc/systemd/network/{{ item.key }}.network"
    mode: 0644
  with_dict: "{{ systemd_networkd_network }}"

# vim: set ts=2 sw=2:
