---
- import_tasks: install/void.yml
  when: ansible_lsb.id is "VoidLinux"

- import_tasks: install/fedora.yml
  when: ansible_lsb.id is "Fedora" or ansible_lsb.id is "CentOS"

- import_tasks: install/debian.yml
  when: ansible_lsb.id is "Debian" or ansible_lsb.id is "Ubuntu"

# TODO: Support more distros (and maybe even Windows one day)
