---
# tasks file for traefik
- name: Create user
  user:
    name: traefik
    groups: docker
    append: yes
  register: userretval

- name: Create traefik base directory
  file:
    path: /opt/traefik
    owner: traefik
    group: traefik
    state: directory
    mode: 0755

- name: Create traefik config directory
  file:
    path: /opt/traefik/config.d
    owner: traefik
    group: traefik
    state: directory
    mode: 0755

- name: Create acme.json
  file:
    path: /opt/traefik/acme.json
    owner: traefik
    group: traefik
    state: touch
    mode: 0600

- name: Template config file
  template:
    src: traefik.yml.j2
    dest: /opt/traefik/config.yml
    owner: traefik
    group: traefik
  notify: restart traefik

- name: template dynamic configs
  template:
    src: "{{ item }}.yml.j2"
    dest: "/opt/traefik/config.d/{{ item }}.yml"
    owner: traefik
    group: traefik
  loop:
    - api-router
    - https-redirect

- name: Deploy traefik-container
  docker_container:
    name: traefik
    image: '{{ traefik_container_image_ref }}'
    network_mode: host
    restart_policy: unless-stopped
#       user: "{{ userretval.uid }}:{{ userretval.group }}"
#       TODO: Make running this as non-root work.
    pull: true
    env: "{{ traefik_container_env }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/traefik/config.yml:/traefik.yml"
      - "/opt/traefik/config.d/:/opt/traefik/config.d/"
      - "/opt/traefik/acme.json:/acme.json"

