---
- name: Start yggdrasil
  ansible.builtin.service:
    name: yggdrasil
    enabled: true
    state: started
  when: ansible_os_family in ["Debian", "RedHat", "Archlinux"]

# This separate entry here is needed because
# the service module does not support runit
- name: Start yggdrasil
  community.general.runit:
    name: yggdrasil
    enabled: true
    state: started
  when: ansible_os_family in ["Void"]
