---
- name: Import void linux tasks
  ansible.builtin.import_tasks: install/void.yml
  when: ansible_os_family == "void"

- name: Import fedora tasks
  ansible.builtin.import_tasks: install/fedora.yml
  when: ansible_os_family == "RedHat"

- name: Import debian tasks
  ansible.builtin.import_tasks: install/debian.yml
  when: ansible_os_family == "Debian"

- name: Import arch tasks
  ansible.builtin.import_tasks: install/arch.yml
  when: ansible_os_family == "Archlinux"

# TODO: Support more distros (and maybe even Windows one day)
