---
- name: Import check tasks
  ansible.builtin.import_tasks: check.yml

- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
  tags: ['prepare', 'prepare-yggdrasil']

- name: Import configuration tasks
  ansible.builtin.import_tasks: configure.yml
  tags: ['deploy', 'deploy-yggdrasil']
