---

- name: Template connection settings for {{ conn.name }}
  become: true
  template:
    src: templates/ipsec.d/connection.conf.j2
    dest: "{{ ipsec_connection_config_file }}"
    mode: "0644"
  notify: update-ipsec-configuration

- name: Template connection settings for {{ conn.name }}
  become: true
  template:
    src: templates/ipsec.d/connection.secret.j2
    dest: "{{ ipsec_connection_secrets_file }}"
    mode: "0644"
  when: conn.ike.auth in ['psk', 'secret']
  notify: update-ipsec-configuration

- name: Ensure connection '{{ conn.name }}' is included in IPsec configuration
  lineinfile:
    dest: /etc/ipsec.conf
    line: "include {{ ipsec_connection_config_file }}"
  notify: update-ipsec-configuration

- name: Ensure secret '{{ conn.name }}' is included in IPsec configuration
  lineinfile:
    dest: /etc/ipsec.secrets
    line: "include {{ ipsec_connection_secrets_file }}"
  notify: update-ipsec-configuration

- name: Ensure ipsec.service is started
  systemd:
    unit: ipsec.service
    state: started
