---

- name: Install strongswan
  apt:
    name:
      - strongswan
      - libstrongswan-standard-plugins
    cache_valid_time: 86400
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
  notify: restart-ipsec-service

#- name: Enable IPv4 forwarding
#  ansible.builtin.blockinfile:
#    dest: /etc/sysctl.conf
#    block: |
#      net.ipv4.ip_forward = 1
#      net.ipv4.conf.all.accept_redirects = 0
#      net.ipv4.conf.all.send_redirects = 0
#  notify: reload-sysctl-configuration

- name: Enable IPv6 forwarding
  ansible.builtin.blockinfile:
    dest: /etc/sysctl.conf
    block: |
      net.ipv6.conf.all.forwarding = 1
  notify: reload-sysctl-configuration

- name: Set up ipsec connection
  include_tasks:
    file: configure-connection.yml
    apply:
      vars:
        ipsec_connection_config_file: "/etc/ipsec.d/{{ conn.name }}.conf"
        ipsec_connection_secrets_file: "/etc/ipsec.d/{{ conn.name }}.secrets"
  loop: "{{ ipsec_connections }}"
  loop_control:
    loop_var: conn
    label: "{{ conn.name }} ({{ conn.local.outside_address }} <-> {{ conn.remote.outside_address }})"
