---

- name: "Write {{ config_dir }}/connections.conf"
  become: true
  template:
    src: templates/swanctl/conf.j2
    dest: "{{ config_dir }}/connections.conf"
    mode: "0644"
  vars:
    data: "{{ config_body.connections }}"
  when: config_body.connections

- name: "Write {{ config_dir }}/secrets.conf"
  become: true
  template:
    src: templates/swanctl/conf.j2
    dest: "{{ config_dir }}/secrets.conf"
    mode: "0600"
  vars:
    data:
      secrets: >-
        {% for (secret_name,secret_body) in config_body.secrets %}
        - {{ secret_body.type ~ secret_name }}:
          {% set id_index = 0 %}
          {% for id_value in secret_body.id %}
          {{ 'id' ~ id_index }}: {{ id_value }}
          {% set id_index = id_index +1 %}
          {% endfor %}
        {% endfor %}
  when: config_body.secrets

- name: Configure Firewall
  include_tasks:
    file: ufw.yml
