---

- name: Force restart IPSec stack with systemd
  systemd:
    unit: strongswan.service
    state: restarted
  listen: service-strongswan-restart

- name: Reload swanctl config files
  command: "swanctl -q"
  listen: swanctl-reload

- name: Force charon to reread strongswan.conf
  command: "swanctl -r"
  listen: swanctl-charon-reload

- name: Restart 
  block:
    - command: "{{ 'swanctl -t --ike ' ~ item.key }}"
    - command: "{{ 'swanctl -i --ike ' ~ item.key }}"
    - command: "{{ 'swanctl -i --child ' ~ item.key }}"
      loop: "{{ lookup (item.value.children) }}"
  loop: "{{ lookup ( _ipsec_restartable_connections ) }}"
  when: ipsec_restart_connections_on_change
  listen: swanctl-restart-connection

- name: Reload /etc/sysctl.conf
  command: sysctl -p
  listen: sysctl-reload
