traefik_enable_docker: true
traefik_enable_api: true
traefik_enable_api_dashboard: true
traefik_enable_api_debug: false
traefik_enable_api_authentication: false
traefik_enable_prometheus: true
traefik_api_users: []
traefik_container_env: {}
traefik_acme_challenge: "HTTP-01"
traefik_acme_enabled: true
traefik_entrypoints:
  - name: web
    config:
      address: ":80"
  - name: web-secure
    config:
      address: ":443"
traefik_metrics_rule: "Host(`{{ traefik_api_host }}`) && Path(`/metrics`)"
traefik_metrics_enable_tls: false

traefik_container_image_ref: "{{ traefik_container_image_name }}:{{ traefik_container_image_tag }}"
traefik_container_image_name: docker.io/traefik
traefik_container_image_tag: v2.2
