---
- name: Install apt key deps
  ansible.builtin.apt:
    name: dirmngr
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: Add apt key
  ansible.builtin.apt_key:
    state: present
    url: https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt
    id: 569130E8CA20FBC4CB3FDE555898470A764B32C9
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: deb http://neilalexander.s3.eu-west-2.amazonaws.com/deb/ debian yggdrasil
    state: present
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2

- name: Install yggdrasil
  ansible.builtin.apt:
    name: yggdrasil
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
