---
- name: Install yggdrasil
  community.general.xbps:
    name: "{{ item }}"
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
  loop:
    - yggdrasil
    - yggdrasilctl
