---
galaxy_info:
  author: Jan Christian Grünhage <jan.christian@gruenhage.xyz>
  description: Install and configure yggdrasil

  license: AGPLv3

  min_ansible_version: 2.10

  platforms:
    - name: Void Linux
      versions: [ any ]
    - name: Debian
      versions:
        - stretch
        - buster
        - bullseye
    - name: Fedora
      versions:
        - 35
        - 36
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - hirsute
        - impish
        - jammy
    - name: ArchLinux # Depends on some aur tool
      versions: [ any ]
    - name: Alpine
      versions: [ any ]

  galaxy_tags: []

dependencies: []
