---
proxy46_user: proxy46
proxy46_base_path: /opt/proxy46
proxy46_base_path_owner: "{{ proxy46_user }}"
proxy46_base_path_group: "{{ proxy46_user }}"
proxy46_base_path_mode: "0750"

proxy46_log_level: error
proxy46_container_name: proxy46

proxy46_container_image_ref: "{{ proxy46_container_image_name }}:{{ proxy46_container_image_tag }}"
proxy46_container_image_name: registry.gitlab.com/famedly/infra/containers/proxy46
proxy46_container_image_tag: "latest"
proxy46_container_pull: true

proxy46_prefix: "{{ famedly_server_host_ipv6 | regex_replace('((::)1|(:)0:1)$', '\\2\\3') }}"
proxy46_dns: "1.1.1.1"
