---
- name: Restart traefik container '{{ traefik_container_name }}'
  listen: "restart_traefik"
  community.docker.docker_container:
    name: "{{ traefik_container_name }}"
    state: "started"
    restart: true
