---

strongswan_openmetrics_vici_exporter_version: 0.1.1

strongswan_openmetrics_vici_exporter_container_port: 8000

strongswan_openmetrics_vici_exporter_container_name: "openmetrics_vici_exporter"
strongswan_openmetrics_vici_exporter_container_env:
  VICI_EXPORTER_VICI_SOCKET: "{{ strongswan_charon_vici_socket }}"
  VICI_EXPORTER_VICI_INTERVAL: "{{ strongswan_openmetrics_vici_exporter_interval }}"
  VICI_EXPORTER_SERVER_ADDRESS: "{{ strongswan_openmetrics_vici_exporter_bind_address | default('[::]') }}"
  VICI_EXPORTER_SERVER_PORT: "{{ strongswan_openmetrics_vici_exporter_container_port }}"

strongswan_openmetrics_vici_exporter_container_ports: []
strongswan_openmetrics_vici_exporter_container_labels: {}
strongswan_openmetrics_vici_exporter_container_volumes:
  - "{{ strongswan_charon_vici_socket ~ ':' ~ strongswan_charon_vici_socket ~ ':rw' }}"
strongswan_openmetrics_vici_exporter_container_restart_policy: "unless-stopped"
strongswan_openmetrics_vici_exporter_container_force_pull: false

strongswan_openmetrics_vici_exporter_container_image_reference: >-
  {{
    strongswan_openmetrics_vici_exporter_container_image_repository
    ~ ":"
    ~ strongswan_openmetrics_vici_exporter_container_image_tag | default('v' ~ strongswan_openmetrics_vici_exporter_version)
  }}
strongswan_openmetrics_vici_exporter_container_image_repository: >-
  {{
    (
      container_registries[strongswan_openmetrics_vici_exporter_container_image_registry]
      | default(strongswan_openmetrics_vici_exporter_container_image_registry)
    )
    ~ "/"
    ~ strongswan_openmetrics_vici_exporter_container_image_namespace | default("")
    ~ strongswan_openmetrics_vici_exporter_container_image_name
  }}
strongswan_openmetrics_vici_exporter_container_image_registry: "docker-oss.nexus.famedly.de"
strongswan_openmetrics_vici_exporter_container_image_name: "openmetrics_vici_exporter"

