---
# tasks file for traefik
- name: Create user
  user:
    name: traefik
    groups: docker
    append: yes
  register: userretval
  tags: ['prepare', 'prepare-traefik']

- name: Create traefik base directory
  file:
    path: "{{ traefik_base_path }}"
    owner: traefik
    group: traefik
    state: directory
    mode: 0755
  tags: ['prepare', 'prepare-traefik']

- name: Create traefik config directory
  file:
    path: "{{ traefik_base_path }}/config.d"
    owner: traefik
    group: traefik
    state: directory
    mode: 0755
  tags: ['prepare', 'prepare-traefik']

- name: Setup ACME
  include_tasks:
    file: acme.yml
    apply:
      tags: ['prepare', 'prepare-traefik']
  tags: ['prepare', 'prepare-traefik']

- name: Template config file
  template:
    src: traefik.yml.j2
    dest: "{{ traefik_base_path }}/config.yml"
    owner: traefik
    group: traefik
  notify: restart traefik
  tags: ['deploy', 'deploy-traefik']

- name: template dynamic configs
  template:
    src: "{{ item }}.yml.j2"
    dest: "{{ traefik_base_path }}/config.d/{{ item }}.yml"
    owner: traefik
    group: traefik
  loop: "{{ traefik_dynamic_configs }}"
  notify: restart traefik
  tags: ['deploy', 'deploy-traefik']

- name: Ensure traefik container image is present
  docker_image:
    name: "{{ traefik_container_image_ref }}"
    force_source: "{{ traefik_container_pull }}"
    source: pull
    state: present
  tags: ['prepare', 'prepare-traefik']

- name: Ensure traefik container is running
  docker_container:
    name: "{{ traefik_container_name }}"
    image: '{{ traefik_container_image_ref }}'
    networks: "{{ traefik_container_networks | default(omit) }}"
    etc_hosts: "{{ traefik_container_etc_hosts }}"
    network_mode: "{{ traefik_container_network_mode }}"
    ports: "{{ traefik_container_ports }}"
    restart_policy: unless-stopped
    state: started
#       user: "{{ userretval.uid }}:{{ userretval.group }}"
#       TODO: Make running this as non-root work.
    labels: "{{ traefik_container_labels_complete }}"
    env: "{{ traefik_container_env }}"
    volumes:
      - "{{ traefik_container_socket }}:/var/run/docker.sock"
      - "{{ traefik_base_path }}/config.yml:/traefik.yml"
      - "{{ traefik_base_path }}/config.d/:{{ traefik_base_path }}/config.d/"
      - "{{ traefik_base_path }}/acme.json:/acme.json"
    healthcheck:
      test: >-
        wget -q --spider http://localhost:8022/ping
  tags: ['deploy', 'deploy-traefik']
