---

- name: Create traefik cert directory
  ansible.builtin.file:
    path: "{{ traefik_cert_path }}"
    state: directory
    owner: "{{ traefik_cert_path_owner }}"
    group: "{{ traefik_cert_path_group }}"
    mode: "{{ traefik_cert_path_mode }}"

- name: Deploy certificates
  ansible.builtin.include_tasks: deploy-manual-cert.yml
  vars:
    fullchain_path: "{{ traefik_cert_path }}/{{ item.name }}-fullchain.pem"
    privkey_path: "{{ traefik_cert_path }}/{{ item.name }}-privkey.pem"
    deployed_cert:
      fullchain: "{{ fullchain_path }}"
      privkey: "{{ privkey_path }}"
  loop: "{{ traefik_certs_to_deploy }}"

- name: Map certificates into container
  ansible.builtin.set_fact:
    traefik_container_volumes: >-2
      {{ traefik_container_volumes + [cert_mapping] }}
  vars:
    cert_mapping: "{{ traefik_cert_path }}:{{ traefik_cert_path }}:ro"
