---

- name: Install and configure StrongSwan for IPsec tunneling
  hosts: [ strongswan ]
  gather_facts: true
  become: true
  become_user: root
  pre_tasks: []
  collections:
    - famedly.network

  roles:
    - role: strongswan
      vars:
        strongswan_deployment_mode: "starter"
        ipsec_connections:
        - name: test
          ike:
            #  rekey_time: 15m
            auth: "secret"
            version: 2
            secret: "bottom secret"
          local_outside_address: "192.168.64.6/24"
          local_inside_address: "10.0.0.6/24"
          remote_outside_address: "192.168.64.5/24"
          remote_inside_address: "10.0.0.5/24"
          child:
            - 1:
              #  life_time: 5m
              remote_allowed_networks:
                - "10.0.0.0/24"
              local_allowed_networks:
                - "10.0.0.0/24"
