---

- name: Install wireguard package (Debian/Ubuntu)
  apt:
    name: wireguard
    state: present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install wireguard package (Fedora)
  dnf:
    name: wireguard-tools
    state: present
  when: ansible_distribution == "Fedora"

- name: Install wireguard package (generic)
  package:
    name: wireguard-tools
    state: present
  when: ansible_distribution not in ['Debian', 'Ubuntu', 'Fedora']
