---
- name: Template config for interface {{ item.iface_name }}
  template:
    dest: "{{ wg_basedir }}/{{ item.iface_name }}.conf"
    src: iface_config.conf.j2
  register: wg_config_template

- name: restart wg-quick@{{ item.iface_name }} if config changed
  systemd:
    name: wg-quick@{{ item.iface_name }}
    state: restarted
  when: wg_config_template.changed

- name: Set systemd unit state for wg-quick@{{ item.iface_name }}
  systemd:
    name: "wg-quick@{{ item.iface_name }}"
    state: "{{ item.systemd_unit_state | default('started') }}"
    enabled: "{{ item.systemd_unit_enabled | default('true') }}"
