---
- name: Restart yggdrasil using ansible.builtin.service
  ansible.builtin.service:
    name: yggdrasil
    enabled: true
    state: restarted
  when: ansible_lsb.id != "Void"
  listen: "restart_yggdrasil"

- name: Restart yggdrasil using community.general.runit
  community.general.runit:
    name: yggdrasil
    enabled: true
    state: restarted
  when: ansible_lsb.id == "Void"
  listen: "restart_yggdrasil"
