---
# handlers file for yggdrasil
- name: Restart yggdrasil using service
  ansible.builtin.service:
    name: yggdrasil
    enabled: true
    state: restarted
  when: ansible_lsb.id != "Void"
  listen: restart yggdrasil

- name: Restart yggdrasil using runit
  community.general.runit:
    name: yggdrasil
    enabled: true
    state: restarted
  when: ansible_lsb.id == "Void"
  listen: restart yggdrasil
