---
- name: Restart yggdrasil using ansible.builtin.service
  ansible.builtin.service:
    name: yggdrasil
    enabled: true
    state: restarted
  when: ansible_os_family in ["Debian", "RedHat", "Archlinux"]
  listen: "restart_yggdrasil"

- name: Restart yggdrasil using community.general.runit
  community.general.runit:
    name: yggdrasil
    enabled: true
    state: restarted
  when: ansible_os_family in ["Void"]
  listen: "restart_yggdrasil"

- name: Restart yggdrasil using dinit
  ansible.builtin.command:
    argv:
      - dinitctl
      - --system
      - restart
      - yggdrasil
  when: ansible_os_family in ["Chimera"]
  listen: "restart_yggdrasil"
